spring:
  datasource:
    driverClassName:
    url: jdbc:postgresql://ec2-54-88-130-244.compute-1.amazonaws.com:5432/dtrkilp0s149h
    username: jfnlzyumoomvtj
    password: 739520e1c6e61e3dca6eee5cb0a1a632b61a1c5f89c241c6a4f6347449f91f63
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    check-location: true
    locations: classpath:/db/migration

server:
  port: 8888
  servlet:
    context-path: /rms-service
  error:
    include-stacktrace: never
    include-path: never

#devtool
devtools:
  livereload:
    enabled: true
  add-properties: true

#swgger
swagger:
  enabled: true

#jwt
jwt:
  secret: alfazidrms

  #api-integration
rms: