spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rms_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  flyway:
    enabled: true
    check-location: true
    locations: classpath:/db/migration

server:
  port: 8888
  servlet:
    context-path: /rms-service
  error:
    include-stacktrace: never
    include-path: never

#devtool
devtools:
  livereload:
    enabled: true
  add-properties: true

#swgger
swagger:
  enabled: true

#jwt
jwt:
  secret: alfazidrms

  #api-integration
rms: