CREATE TABLE outlet (
   outlet_id VARCHAR(36) NOT NULL,
   outlet_name VARCHAR(60) NOT NULL,
   phone_number VARCHAR(15) NOT NULL,
   phone_number2 VARCHAR(15) NULL,
   fax_number VARCHAR(15) NULL,
   email VARCHAR(30) NOT NULL,
   website VARCHAR(30) NULL,
   country_id VARCHAR(3) NOT NULL,
   province_id VARCHAR(36) NULL,
   district_id VARCHAR(36) NULL,
   sub_district_id VARCHAR(36) NULL,
   village_id VARCHAR(36) NULL,
   city_id VARCHAR(36) NULL,
   currency_id VARCHAR(36) NOT NULL,
   postcode INTEGER NULL,
   address VARCHAR(250) NOT NULL,
   contact_person VARCHAR(30) NOT NULL,
   contact_number VARCHAR(15) NOT NULL,
   tax_registration_number VARCHAR(30) NULL,
   letter_of_business_permit VARCHAR(30) NULL,
   image VARCHAR(1280) NULL,
   active BOOLEAN DEFAULT true,
   created_by VARCHAR(36) NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_by VARCHAR(36) NULL,
   updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (outlet_id)
 );
