CREATE TABLE employee (
   employee_id VARCHAR(36) NOT NULL,
   employee_code VARCHAR(10) NOT NULL,
   first_name VARCHAR(30) NOT NULL,
   last_name VARCHAR(30) NULL,
   nick_name VARCHAR(30) NOT NULL,
   phone_number VARCHAR(15) NOT NULL,
   phone_number2 VARCHAR(15) NOT NULL,
   email VARCHAR(30) NULL,
   country_id VARCHAR(36) NOT NULL,
   province_id VARCHAR(36) NULL,
   district_id VARCHAR(36) NULL,
   sub_district_id VARCHAR(36) NULL,
   village_id VARCHAR(36) NULL,
   city_id VARCHAR(36) NULL,
   postcode INTEGER NULL,
   address  VARCHAR(250) NOT NULL,
   place_of_birth VARCHAR(250) NOT NULL,
   birth_of_date DATE,
   age INTEGER,
   marital_status VARCHAR(1) NOT NULL,
   occupation_id VARCHAR(36) NOT NULL,
   sex VARCHAR(1) NOT NULL,
   id_card_type VARCHAR(1) NOT NULL,
   id_card_number VARCHAR(30) NOT NULL,
   tax_id VARCHAR(30) NOT NULL,
   insurance_id VARCHAR(36) NULL,
   insurance_number VARCHAR(30) NULL,
   image VARCHAR(1280) NULL,
   outlet_id VARCHAR(36) NOT NULL,
   active VARCHAR(1) NOT NULL,
   created_by VARCHAR(36) NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_by VARCHAR(36) NULL,
   updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (employee_id)
 );
