CREATE TABLE product (
   product_id VARCHAR(36) NOT NULL,
   sku VARCHAR(20) NOT NULL,
   plu VARCHAR(20) NOT NULL,
   barcode VARCHAR(30) NOT NULL,
   product_name VARCHAR(60) NOT NULL,
   category_id VARCHAR(36)  NOT NULL,
   brand_id VARCHAR(36)  NOT NULL,
   type_id VARCHAR(36)  NOT NULL,
   uom_id VARCHAR(36) NOT NULL,
   size INTEGER NULL,
   tag VARCHAR(10) NULL,
   retail_price DECIMAL(15,2) NOT NULL,
   discount_price DECIMAL(15,2)  NULL,
   base_price DECIMAL(15,2) NOT NULL,
   is_scale Boolean NULL,
   weight FLOAT NULL,
   supplier_id VARCHAR(36) NOT NULL,
   outlet_id VARCHAR(36)  NOT NULL,
   image  VARCHAR(255) NULL,
   initial_stock INTEGER NULL,
   remark VARCHAR(255) NULL,
    active BOOLEAN DEFAULT true,
   created_by VARCHAR(36) NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_by VARCHAR(36) NULL,
   updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (product_id)
 );